Update Docs and Sample to use new API for adding custom Navigators
google/accompanist pull request #746
Opened 2021-09-29 16:08 UTC by jossiwolf

To be merged once Nav 2.4.0 Alpha 10 is released :)

Fixes #744

2021-09-29 18:27 UTC, ianhanniballake commented
Navigation 2.4.0-alpha10 is out now so I think you can update the dependency now.

2021-09-29 18:31 UTC, jossiwolf commented
Will do, thanks for the heads up! The snapshot was failing to resolve a dependency

2021-09-29 21:18 UTC, jossiwolf commented
The one test that failed was a [Pager test](https://github.com/google/accompanist/pull/746/checks?check_run_id=3748866513), there shouldn't be any connection.

2021-09-30 00:10 UTC, ianhanniballake requested changes

2021-09-30 00:10 UTC, ianhanniballake commented on navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
>              navController.navigatorProvider += navigator
You don't need this line anymore

2021-09-30 06:29 UTC, jossiwolf commented on navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
>              navController.navigatorProvider += navigator
Thanks 🙏

2021-09-30 07:35 UTC, chrisbanes approved these changes

2021-09-30 07:35 UTC, merged