[Material-Navigation] Add navigator-level skip half expanded flag for BottomSheetNavigator.kt
google/accompanist pull request #961
Opened 2022-01-19 14:43 UTC by colintheshots-meetup

This adds a skip half expanded flag to the rememberBottomSheetNavigator() function thereby fixing #657 for the navigator only.

Discussion on this PR before rebase: https://github.com/google/accompanist/pull/957

2022-01-21 15:50 UTC, jossiwolf requested changes

2022-01-21 18:15 UTC, colintheshots commented on navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/HalfExpandedTests.kt
> +                        bottomSheet("bottomSheet") {
I updated the PR. Take a look. 👀

2022-01-23 12:17 UTC, jossiwolf approved these changes

2022-01-24 08:16 UTC, bentrengrove approved these changes

2022-01-24 21:36 UTC, merged